import {
  siAngular,
  siAnsible,
  siApache,
  siApachecassandra,
  siApachetomcat,
  siArgo,
  siAuth0,
  siC,
  siCloudflare,
  siCplusplus,
  siCss,
  siDart,
  siDjango,
  siDocker,
  siDotnet,
  siElasticsearch,
  siElixir,
  siExpress,
  siFastapi,
  siFastify,
  siFirebase,
  siFlask,
  siFlutter,
  siGin,
  siGit,
  siGithub,
  siGithubactions,
  siGitlab,
  siGo,
  siGrafana,
  siGraphql,
  siHelm,
  siHtml5,
  siJavascript,
  siJenkins,
  siKotlin,
  siKubernetes,
  siLaravel,
  siLinux,
  siMariadb,
  siMongodb,
  siMysql,
  siNeo4j,
  siNestjs,
  siNextdotjs,
  siNginx,
  siNodedotjs,
  siNuxt,
  siOpenjdk,
  siPhp,
  siPostgresql,
  siPrometheus,
  siPython,
  siReact,
  siRedis,
  siRedhatopenshift,
  siRemix,
  siRuby,
  siRubyonrails,
  siRust,
  siScala,
  siSpringboot,
  siSqlite,
  siSvelte,
  siSwift,
  siTailwindcss,
  siTerraform,
  siTraefikproxy,
  siTypescript,
  siUbuntu,
  siVuedotjs,
  type SimpleIcon,
} from 'simple-icons'

export const BRAND_ICONS: Partial<Record<string, SimpleIcon>> = {
  javascript: siJavascript,
  typescript: siTypescript,
  python: siPython,
  java: siOpenjdk,
  csharp: siDotnet,
  go: siGo,
  php: siPhp,
  ruby: siRuby,
  rust: siRust,
  kotlin: siKotlin,
  swift: siSwift,
  cpp: siCplusplus,
  c: siC,
  scala: siScala,
  dart: siDart,
  elixir: siElixir,
  react: siReact,
  vue: siVuedotjs,
  angular: siAngular,
  nextjs: siNextdotjs,
  nuxt: siNuxt,
  svelte: siSvelte,
  remix: siRemix,
  html: siHtml5,
  css: siCss,
  tailwind: siTailwindcss,
  flutter: siFlutter,
  'react-native': siReact,
  nodejs: siNodedotjs,
  express: siExpress,
  nestjs: siNestjs,
  spring: siSpringboot,
  django: siDjango,
  fastapi: siFastapi,
  flask: siFlask,
  laravel: siLaravel,
  dotnet: siDotnet,
  aspnet: siDotnet,
  rails: siRubyonrails,
  gin: siGin,
  fastify: siFastify,
  graphql: siGraphql,
  postgres: siPostgresql,
  mysql: siMysql,
  mariadb: siMariadb,
  mongodb: siMongodb,
  redis: siRedis,
  elastic: siElasticsearch,
  sqlite: siSqlite,
  cassandra: siApachecassandra,
  neo4j: siNeo4j,
  firebase: siFirebase,
  nginx: siNginx,
  apache: siApache,
  tomcat: siApachetomcat,
  linux: siLinux,
  ubuntu: siUbuntu,
  docker: siDocker,
  k8s: siKubernetes,
  openshift: siRedhatopenshift,
  cloudflare: siCloudflare,
  traefik: siTraefikproxy,
  github: siGithub,
  gitlab: siGitlab,
  jenkins: siJenkins,
  terraform: siTerraform,
  ansible: siAnsible,
  prometheus: siPrometheus,
  grafana: siGrafana,
  git: siGit,
  cicd: siGithubactions,
  helm: siHelm,
  argocd: siArgo,
  auth: siAuth0,
  aks: siKubernetes,
}
