import type { CatalogItem, CategoryId } from './types'

export const CATEGORIES: { id: CategoryId; label: string }[] = [
  { id: 'architecture', label: 'Arquitetura' },
  { id: 'languages', label: 'Linguagens' },
  { id: 'frontend', label: 'Frontend' },
  { id: 'backend', label: 'Backend & APIs' },
  { id: 'databases', label: 'Bancos de dados' },
  { id: 'servers', label: 'Servidores & Infra' },
  { id: 'aws', label: 'AWS' },
  { id: 'azure', label: 'Azure' },
  { id: 'devops', label: 'DevOps' },
]

function item(
  id: string,
  name: string,
  category: CategoryId,
  color: string,
  initials: string,
): CatalogItem {
  return { id, name, category, color, initials }
}

export const CATALOG: CatalogItem[] = [
  item('users', 'Usuários', 'architecture', '#5b8def', 'USR'),
  item('browser', 'Browser', 'architecture', '#6aa9ff', 'WEB'),
  item('mobile', 'App Mobile', 'architecture', '#3dd6c6', 'MOB'),
  item('api', 'API', 'architecture', '#7c8cff', 'API'),
  item('gateway', 'API Gateway', 'architecture', '#8b7cff', 'GW'),
  item('lb', 'Load Balancer', 'architecture', '#4ec3f7', 'LB'),
  item('cdn', 'CDN', 'architecture', '#47c1a8', 'CDN'),
  item('queue', 'Fila', 'architecture', '#f0b429', 'FIL'),
  item('cache', 'Cache', 'architecture', '#e36a6a', 'CHE'),
  item('auth', 'Auth', 'architecture', '#c084fc', 'ATH'),
  item('storage', 'Storage', 'architecture', '#94a3b8', 'STO'),
  item('worker', 'Worker', 'architecture', '#fb923c', 'WRK'),
  item('webhook', 'Webhook', 'architecture', '#22d3ee', 'WHK'),
  item('bus', 'Message Bus', 'architecture', '#f59e0b', 'BUS'),

  item('javascript', 'JavaScript', 'languages', '#f7df1e', 'JS'),
  item('typescript', 'TypeScript', 'languages', '#3178c6', 'TS'),
  item('python', 'Python', 'languages', '#3776ab', 'PY'),
  item('java', 'Java', 'languages', '#e76f00', 'JV'),
  item('csharp', 'C#', 'languages', '#68217a', 'C#'),
  item('go', 'Go', 'languages', '#00add8', 'GO'),
  item('php', 'PHP', 'languages', '#777bb4', 'PHP'),
  item('ruby', 'Ruby', 'languages', '#cc342d', 'RB'),
  item('rust', 'Rust', 'languages', '#dea584', 'RS'),
  item('kotlin', 'Kotlin', 'languages', '#7f52ff', 'KT'),
  item('swift', 'Swift', 'languages', '#f05138', 'SW'),
  item('cpp', 'C++', 'languages', '#00599c', 'C+'),
  item('c', 'C', 'languages', '#a8b9cc', 'C'),
  item('scala', 'Scala', 'languages', '#dc322f', 'SC'),
  item('dart', 'Dart', 'languages', '#0175c2', 'DT'),
  item('elixir', 'Elixir', 'languages', '#6e4a7e', 'ELX'),

  item('react', 'React', 'frontend', '#61dafb', 'RCT'),
  item('vue', 'Vue', 'frontend', '#42b883', 'VUE'),
  item('angular', 'Angular', 'frontend', '#dd0031', 'NG'),
  item('nextjs', 'Next.js', 'frontend', '#e4e4e7', 'NXT'),
  item('nuxt', 'Nuxt', 'frontend', '#00dc82', 'NU'),
  item('svelte', 'Svelte', 'frontend', '#ff3e00', 'SV'),
  item('remix', 'Remix', 'frontend', '#e8e8ec', 'RMX'),
  item('html', 'HTML5', 'frontend', '#e34f26', 'HT'),
  item('css', 'CSS3', 'frontend', '#1572b6', 'CSS'),
  item('tailwind', 'Tailwind', 'frontend', '#38bdf8', 'TW'),
  item('flutter', 'Flutter', 'frontend', '#02569b', 'FLU'),
  item('react-native', 'React Native', 'frontend', '#61dafb', 'RN'),

  item('nodejs', 'Node.js', 'backend', '#68a063', 'ND'),
  item('express', 'Express', 'backend', '#d4d4d8', 'EXP'),
  item('nestjs', 'NestJS', 'backend', '#e0234e', 'NS'),
  item('spring', 'Spring Boot', 'backend', '#6db33f', 'SP'),
  item('django', 'Django', 'backend', '#092e20', 'DJ'),
  item('fastapi', 'FastAPI', 'backend', '#009688', 'FA'),
  item('flask', 'Flask', 'backend', '#ececec', 'FLK'),
  item('laravel', 'Laravel', 'backend', '#ff2d20', 'LV'),
  item('dotnet', '.NET', 'backend', '#512bd4', 'NET'),
  item('aspnet', 'ASP.NET', 'backend', '#512bd4', 'ASP'),
  item('rails', 'Rails', 'backend', '#cc0000', 'RL'),
  item('gin', 'Gin', 'backend', '#00add8', 'GIN'),
  item('fastify', 'Fastify', 'backend', '#000000', 'FY'),
  item('graphql', 'GraphQL', 'backend', '#e535ab', 'GQL'),
  item('rest', 'REST API', 'backend', '#4f8ef7', 'RST'),
  item('grpc', 'gRPC', 'backend', '#244c5a', 'RPC'),

  item('postgres', 'PostgreSQL', 'databases', '#336791', 'PG'),
  item('mysql', 'MySQL', 'databases', '#4479a1', 'MY'),
  item('mariadb', 'MariaDB', 'databases', '#c0765a', 'MD'),
  item('sqlserver', 'SQL Server', 'databases', '#cc2927', 'SS'),
  item('mongodb', 'MongoDB', 'databases', '#47a248', 'MG'),
  item('redis', 'Redis', 'databases', '#dc382d', 'RD'),
  item('elastic', 'Elasticsearch', 'databases', '#fecc1b', 'ES'),
  item('oracle', 'Oracle', 'databases', '#f80000', 'OR'),
  item('sqlite', 'SQLite', 'databases', '#003b57', 'LQ'),
  item('cassandra', 'Cassandra', 'databases', '#1287b1', 'CS'),
  item('dynamodb', 'DynamoDB', 'databases', '#4053d6', 'DY'),
  item('cosmos', 'Cosmos DB', 'databases', '#3ea6ef', 'CO'),
  item('neo4j', 'Neo4j', 'databases', '#018bff', 'N4'),
  item('firebase', 'Firebase', 'databases', '#ffca28', 'FB'),

  item('nginx', 'Nginx', 'servers', '#009639', 'NX'),
  item('apache', 'Apache', 'servers', '#d22128', 'AP'),
  item('iis', 'IIS', 'servers', '#00bcf2', 'IIS'),
  item('tomcat', 'Tomcat', 'servers', '#d1a041', 'TM'),
  item('haproxy', 'HAProxy', 'servers', '#1e4d2b', 'HA'),
  item('linux', 'Linux', 'servers', '#fcc624', 'LX'),
  item('windows-server', 'Windows Server', 'servers', '#00a4ef', 'WIN'),
  item('ubuntu', 'Ubuntu', 'servers', '#e95420', 'UB'),
  item('docker', 'Docker', 'servers', '#2496ed', 'DK'),
  item('k8s', 'Kubernetes', 'servers', '#326ce5', 'K8'),
  item('openshift', 'OpenShift', 'servers', '#ee0000', 'OS'),
  item('cloudflare', 'Cloudflare', 'servers', '#f38020', 'CF'),
  item('traefik', 'Traefik', 'servers', '#24a1c1', 'TR'),

  item('ec2', 'EC2', 'aws', '#ed7100', 'EC2'),
  item('s3', 'S3', 'aws', '#3f8624', 'S3'),
  item('lambda', 'Lambda', 'aws', '#ed7100', 'λ'),
  item('rds', 'RDS', 'aws', '#3b48cc', 'RDS'),
  item('ecs', 'ECS', 'aws', '#ed7100', 'ECS'),
  item('eks', 'EKS', 'aws', '#ed7100', 'EKS'),
  item('fargate', 'Fargate', 'aws', '#ed7100', 'FG'),
  item('cloudfront', 'CloudFront', 'aws', '#8c4fff', 'CF'),
  item('apigw-aws', 'API Gateway', 'aws', '#ed7100', 'AGW'),
  item('sqs', 'SQS', 'aws', '#ed7100', 'SQS'),
  item('sns', 'SNS', 'aws', '#ed7100', 'SNS'),
  item('dynamo-aws', 'DynamoDB', 'aws', '#3b48cc', 'DDB'),
  item('cloudwatch', 'CloudWatch', 'aws', '#e7157b', 'CW'),
  item('iam', 'IAM', 'aws', '#dd344c', 'IAM'),
  item('vpc', 'VPC', 'aws', '#8c4fff', 'VPC'),
  item('route53', 'Route 53', 'aws', '#8c4fff', 'R53'),
  item('elasticache', 'ElastiCache', 'aws', '#3b48cc', 'EC'),
  item('aurora', 'Aurora', 'aws', '#3b48cc', 'AU'),
  item('cognito', 'Cognito', 'aws', '#dd344c', 'CG'),
  item('stepfn', 'Step Functions', 'aws', '#ed7100', 'SF'),
  item('eventbridge', 'EventBridge', 'aws', '#e7157b', 'EB'),
  item('alb', 'ALB', 'aws', '#8c4fff', 'ALB'),
  item('nlb', 'NLB', 'aws', '#8c4fff', 'NLB'),
  item('cfn', 'CloudFormation', 'aws', '#e7157b', 'CFN'),
  item('secrets', 'Secrets Manager', 'aws', '#dd344c', 'SM'),
  item('amplify', 'Amplify', 'aws', '#ed7100', 'AMP'),
  item('appsync', 'AppSync', 'aws', '#ed7100', 'AS'),
  item('glue', 'Glue', 'aws', '#3b48cc', 'GL'),
  item('athena', 'Athena', 'aws', '#3b48cc', 'AT'),
  item('redshift', 'Redshift', 'aws', '#3b48cc', 'RS'),
  item('beanstalk', 'Elastic Beanstalk', 'aws', '#3b48cc', 'EB'),
  item('waf', 'WAF', 'aws', '#dd344c', 'WAF'),
  item('kinesis', 'Kinesis', 'aws', '#3b48cc', 'KN'),

  item('vm-azure', 'Virtual Machines', 'azure', '#0078d4', 'VM'),
  item('appservice', 'App Service', 'azure', '#0078d4', 'AS'),
  item('az-functions', 'Azure Functions', 'azure', '#3999c6', 'FN'),
  item('aks', 'AKS', 'azure', '#326ce5', 'AKS'),
  item('container-apps', 'Container Apps', 'azure', '#0078d4', 'CA'),
  item('az-sql', 'Azure SQL', 'azure', '#0078d4', 'SQL'),
  item('blob', 'Blob Storage', 'azure', '#0078d4', 'BLB'),
  item('cosmos-az', 'Cosmos DB', 'azure', '#3ea6ef', 'CDB'),
  item('entra', 'Entra ID', 'azure', '#00bcf2', 'ENT'),
  item('servicebus', 'Service Bus', 'azure', '#0078d4', 'SB'),
  item('eventhubs', 'Event Hubs', 'azure', '#0078d4', 'EH'),
  item('keyvault', 'Key Vault', 'azure', '#0078d4', 'KV'),
  item('apim', 'API Management', 'azure', '#0078d4', 'APM'),
  item('frontdoor', 'Front Door', 'azure', '#0078d4', 'FD'),
  item('appgw', 'Application Gateway', 'azure', '#0078d4', 'AG'),
  item('azdo', 'Azure DevOps', 'azure', '#0078d4', 'ADO'),
  item('appinsights', 'App Insights', 'azure', '#0078d4', 'AI'),
  item('az-redis', 'Azure Redis', 'azure', '#dc382d', 'RD'),
  item('logicapps', 'Logic Apps', 'azure', '#0078d4', 'LA'),
  item('az-storage', 'Azure Storage', 'azure', '#0078d4', 'ST'),
  item('flexible-pg', 'PostgreSQL Flexible', 'azure', '#336791', 'PG'),
  item('az-lb', 'Load Balancer', 'azure', '#0078d4', 'LB'),
  item('vnet', 'Virtual Network', 'azure', '#0078d4', 'VN'),
  item('az-cdn', 'Azure CDN', 'azure', '#0078d4', 'CDN'),
  item('eventgrid', 'Event Grid', 'azure', '#0078d4', 'EG'),
  item('bicep', 'Bicep / ARM', 'azure', '#34d399', 'BP'),

  item('github', 'GitHub', 'devops', '#e6edf3', 'GH'),
  item('gitlab', 'GitLab', 'devops', '#fc6d26', 'GL'),
  item('jenkins', 'Jenkins', 'devops', '#d33833', 'JK'),
  item('terraform', 'Terraform', 'devops', '#7b42bc', 'TF'),
  item('ansible', 'Ansible', 'devops', '#ee0000', 'AN'),
  item('prometheus', 'Prometheus', 'devops', '#e6522c', 'PR'),
  item('grafana', 'Grafana', 'devops', '#f46800', 'GF'),
  item('git', 'Git', 'devops', '#f05032', 'GIT'),
  item('cicd', 'CI / CD', 'devops', '#38bdf8', 'CI'),
  item('helm', 'Helm', 'devops', '#0f1689', 'HM'),
  item('argocd', 'Argo CD', 'devops', '#ef7b4d', 'AR'),
]

export const CATALOG_BY_ID = new Map(CATALOG.map((entry) => [entry.id, entry]))
